name: iOS build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: example

      - name: Install dependencies
        run: yarn --cwd example --frozen-lockfile

      - name: Install pods dependency
        run: pod repo update

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install Gem dependencies
        run: gem install bundler:2.4.10

      - name: Install package dependencies
        run: npm run bootstrap

      - name: Install pods
        run: yarn pod-install

      - name: Write Config.xcconfig
        run: echo MAPS_API_KEY=AIzaSyAKnnWFftBUzoQivzhRnEmZhg6FZ3gSlp4 >> example/ios/Config.xcconfig

      - name: Build clean project
        run: |
          xcodebuild clean -workspace example/ios/rnmshowcase.xcworkspace -scheme rnmshowcase

      - name: Build iOS
        run: xcodebuild -workspace example/ios/rnmshowcase.xcworkspace -scheme rnmshowcase -configuration Debug -sdk iphonesimulator
